### ISSUE TITLE
Error reading global state of application after deploying smart contract

### ISSUE THREAD

**Issue by connorjcantrell** [connorjcantrell/counter_smart_contract#1]
My smart contract successfully deploys, however I am receiving an error when attempting to print my newly created app's `global-state`. Why does my app not have a `global-state` parameter?

https://github.com/connorjcantrell/counter_smart_contract/blob/4219abd365f25e36cf18a3d6bc336347693ec232/deploy.py#L87

```
  File "path/to/github.com/connorjcantrell/simple_counter_smart_contract/deploy.py", line 96, in <module>
    init()
  File "path/to/github.com/connorjcantrell/simple_counter_smart_contract/deploy.py", line 87, in init
    read_global_state(
  File "/path/to/github.com/connorjcantrell/simple_counter_smart_contract/helpers.py", line 170, in read_global_state
    return format_state(app["params"]["global-state"])
KeyError: 'global-state'
```

**Comment by fabrice102** [comment]
The issue is that your approval code is actually doing nothing as it just returns `Int(1)`:

https://github.com/connorjcantrell/counter_smart_contract/blob/4219abd365f25e36cf18a3d6bc336347693ec232/contract.py#L61

You need to return `program` instead.

Since the code does nothing, it actually does not create anything in the global state, in which case the `"global-state"` key is not present.

You can easily confirm it using the sandbox (assuming your app id is 1):
```bash
$ ./sandbox goal app read --global --app-id 1
null%
```
